%% <module> pizza
% Autogenerated by rdfs2pl -- see https://github.com/cmungall/rdfs2pl/

:-module(pizza,[closedPizza/1,emptyPizza/1,fishPizza_Closed/1,fishPizza_Open/1,fishTopping/1,gas/1,iceCream/1,liquid/1,liquidSolidIceCream/1,materialState/1,meatAndFishPizza_Closed/1,meatAndFishPizza_Open/1,meatFishAndVegetarianPizza_Closed/1,meatFishAndVegetarianPizza_Open/1,meatPizza_Closed/1,meatPizza_Open/1,meatTopping/1,meltedIceCream/1,oneToppingPizza/1,openPizza/1,pizza/1,pizzaDomainConcept/1,pizzaTopping/1,solid/1,testPizza/1,vegePizza01/1,vegePizza02/1,vegePizza03/1,vegePizza04/1,vegePizza05/1,vegePizza06/1,vegePizza07/1,vegePizza08/1,vegePizza09/1,vegePizza10/1,vegePizza11/1,vegetarianTopping/1,vegetarianToppingsPizza_Closed/1,vegetarianToppingsPizza_Open/1,hasMaterialState/2,hasTopping/2,hasMaterialState/3,hasTopping/3,op(300,xfy,hasMaterialState),op(300,xfy,hasTopping)]).
:-use_module(library(semweb/rdf11)).
:-use_module(library(semweb/rdfs)).

:-op(300,xfy,hasMaterialState).
:-op(300,xfy,hasTopping).

:-rdf_meta pizza:closedPizza(r).

:-rdf_meta pizza:emptyPizza(r).

:-rdf_meta pizza:fishPizza_Closed(r).

:-rdf_meta pizza:fishPizza_Open(r).

:-rdf_meta pizza:fishTopping(r).

:-rdf_meta pizza:gas(r).

:-rdf_meta pizza:iceCream(r).

:-rdf_meta pizza:liquid(r).

:-rdf_meta pizza:liquidSolidIceCream(r).

:-rdf_meta pizza:materialState(r).

:-rdf_meta pizza:meatAndFishPizza_Closed(r).

:-rdf_meta pizza:meatAndFishPizza_Open(r).

:-rdf_meta pizza:meatFishAndVegetarianPizza_Closed(r).

:-rdf_meta pizza:meatFishAndVegetarianPizza_Open(r).

:-rdf_meta pizza:meatPizza_Closed(r).

:-rdf_meta pizza:meatPizza_Open(r).

:-rdf_meta pizza:meatTopping(r).

:-rdf_meta pizza:meltedIceCream(r).

:-rdf_meta pizza:oneToppingPizza(r).

:-rdf_meta pizza:openPizza(r).

:-rdf_meta pizza:pizza(r).

:-rdf_meta pizza:pizzaDomainConcept(r).

:-rdf_meta pizza:pizzaTopping(r).

:-rdf_meta pizza:solid(r).

:-rdf_meta pizza:testPizza(r).

:-rdf_meta pizza:vegePizza01(r).

:-rdf_meta pizza:vegePizza02(r).

:-rdf_meta pizza:vegePizza03(r).

:-rdf_meta pizza:vegePizza04(r).

:-rdf_meta pizza:vegePizza05(r).

:-rdf_meta pizza:vegePizza06(r).

:-rdf_meta pizza:vegePizza07(r).

:-rdf_meta pizza:vegePizza08(r).

:-rdf_meta pizza:vegePizza09(r).

:-rdf_meta pizza:vegePizza10(r).

:-rdf_meta pizza:vegePizza11(r).

:-rdf_meta pizza:vegetarianTopping(r).

:-rdf_meta pizza:vegetarianToppingsPizza_Closed(r).

:-rdf_meta pizza:vegetarianToppingsPizza_Open(r).

:-rdf_meta pizza:hasMaterialState(r,r).

:-rdf_meta pizza:hasTopping(r,r).

:-rdf_meta pizza:subclass_of_hasMaterialState(r,r).

:-rdf_meta pizza:subclass_of_hasTopping(r,r).

:-rdf_meta pizza:hasMaterialState(r,r,g).

:-rdf_meta pizza:hasTopping(r,r,g).

%! closedPizza(I)
%
%  Any instance of <http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#ClosedPizza>
%
pizza:closedPizza(I):-rdfs_individual_of(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#ClosedPizza').

%! emptyPizza(I)
%
%  Any instance of <http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#EmptyPizza>
%
pizza:emptyPizza(I):-rdfs_individual_of(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#EmptyPizza').

%! fishPizza_Closed(I)
%
%  Any instance of <http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#FishPizza-Closed>
%
pizza:fishPizza_Closed(I):-rdfs_individual_of(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#FishPizza-Closed').

%! fishPizza_Open(I)
%
%  Any instance of <http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#FishPizza-Open>
%
pizza:fishPizza_Open(I):-rdfs_individual_of(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#FishPizza-Open').

%! fishTopping(I)
%
%  Any instance of <http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#FishTopping>
%
pizza:fishTopping(I):-rdfs_individual_of(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#FishTopping').

%! gas(I)
%
%  Any instance of <http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#Gas>
%
pizza:gas(I):-rdfs_individual_of(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#Gas').

%! iceCream(I)
%
%  Any instance of <http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#IceCream>
%
pizza:iceCream(I):-rdfs_individual_of(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#IceCream').

%! liquid(I)
%
%  Any instance of <http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#Liquid>
%
pizza:liquid(I):-rdfs_individual_of(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#Liquid').

%! liquidSolidIceCream(I)
%
%  Any instance of <http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#LiquidSolidIceCream>
%
pizza:liquidSolidIceCream(I):-rdfs_individual_of(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#LiquidSolidIceCream').

%! materialState(I)
%
%  Any instance of <http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#MaterialState>
%
pizza:materialState(I):-rdfs_individual_of(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#MaterialState').

%! meatAndFishPizza_Closed(I)
%
%  Any instance of <http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#MeatAndFishPizza-Closed>
%
pizza:meatAndFishPizza_Closed(I):-rdfs_individual_of(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#MeatAndFishPizza-Closed').

%! meatAndFishPizza_Open(I)
%
%  Any instance of <http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#MeatAndFishPizza-Open>
%
pizza:meatAndFishPizza_Open(I):-rdfs_individual_of(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#MeatAndFishPizza-Open').

%! meatFishAndVegetarianPizza_Closed(I)
%
%  Any instance of <http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#MeatFishAndVegetarianPizza-Closed>
%
pizza:meatFishAndVegetarianPizza_Closed(I):-rdfs_individual_of(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#MeatFishAndVegetarianPizza-Closed').

%! meatFishAndVegetarianPizza_Open(I)
%
%  Any instance of <http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#MeatFishAndVegetarianPizza-Open>
%
pizza:meatFishAndVegetarianPizza_Open(I):-rdfs_individual_of(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#MeatFishAndVegetarianPizza-Open').

%! meatPizza_Closed(I)
%
%  Any instance of <http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#MeatPizza-Closed>
%
pizza:meatPizza_Closed(I):-rdfs_individual_of(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#MeatPizza-Closed').

%! meatPizza_Open(I)
%
%  Any instance of <http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#MeatPizza-Open>
%
pizza:meatPizza_Open(I):-rdfs_individual_of(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#MeatPizza-Open').

%! meatTopping(I)
%
%  Any instance of <http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#MeatTopping>
%
pizza:meatTopping(I):-rdfs_individual_of(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#MeatTopping').

%! meltedIceCream(I)
%
%  Any instance of <http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#MeltedIceCream>
%
pizza:meltedIceCream(I):-rdfs_individual_of(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#MeltedIceCream').

%! oneToppingPizza(I)
%
%  Any instance of <http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#OneToppingPizza>
%
pizza:oneToppingPizza(I):-rdfs_individual_of(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#OneToppingPizza').

%! openPizza(I)
%
%  Any instance of <http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#OpenPizza>
%
pizza:openPizza(I):-rdfs_individual_of(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#OpenPizza').

%! pizza(I)
%
%  Any instance of <http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#Pizza>
%
pizza:pizza(I):-rdfs_individual_of(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#Pizza').

%! pizzaDomainConcept(I)
%
%  Any instance of <http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#PizzaDomainConcept>
%
pizza:pizzaDomainConcept(I):-rdfs_individual_of(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#PizzaDomainConcept').

%! pizzaTopping(I)
%
%  Any instance of <http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#PizzaTopping>
%
pizza:pizzaTopping(I):-rdfs_individual_of(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#PizzaTopping').

%! solid(I)
%
%  Any instance of <http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#Solid>
%
pizza:solid(I):-rdfs_individual_of(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#Solid').

%! testPizza(I)
%
%  Any instance of <http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#TestPizza>
%
pizza:testPizza(I):-rdfs_individual_of(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#TestPizza').

%! vegePizza01(I)
%
%  Any instance of <http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#VegePizza01>
%
pizza:vegePizza01(I):-rdfs_individual_of(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#VegePizza01').

%! vegePizza02(I)
%
%  Any instance of <http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#VegePizza02>
%
pizza:vegePizza02(I):-rdfs_individual_of(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#VegePizza02').

%! vegePizza03(I)
%
%  Any instance of <http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#VegePizza03>
%
pizza:vegePizza03(I):-rdfs_individual_of(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#VegePizza03').

%! vegePizza04(I)
%
%  Any instance of <http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#VegePizza04>
%
pizza:vegePizza04(I):-rdfs_individual_of(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#VegePizza04').

%! vegePizza05(I)
%
%  Any instance of <http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#VegePizza05>
%
pizza:vegePizza05(I):-rdfs_individual_of(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#VegePizza05').

%! vegePizza06(I)
%
%  Any instance of <http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#VegePizza06>
%
pizza:vegePizza06(I):-rdfs_individual_of(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#VegePizza06').

%! vegePizza07(I)
%
%  Any instance of <http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#VegePizza07>
%
pizza:vegePizza07(I):-rdfs_individual_of(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#VegePizza07').

%! vegePizza08(I)
%
%  Any instance of <http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#VegePizza08>
%
pizza:vegePizza08(I):-rdfs_individual_of(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#VegePizza08').

%! vegePizza09(I)
%
%  Any instance of <http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#VegePizza09>
%
pizza:vegePizza09(I):-rdfs_individual_of(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#VegePizza09').

%! vegePizza10(I)
%
%  Any instance of <http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#VegePizza10>
%
pizza:vegePizza10(I):-rdfs_individual_of(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#VegePizza10').

%! vegePizza11(I)
%
%  Any instance of <http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#VegePizza11>
%
pizza:vegePizza11(I):-rdfs_individual_of(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#VegePizza11').

%! vegetarianTopping(I)
%
%  Any instance of <http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#VegetarianTopping>
%
pizza:vegetarianTopping(I):-rdfs_individual_of(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#VegetarianTopping').

%! vegetarianToppingsPizza_Closed(I)
%
%  Any instance of <http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#VegetarianToppingsPizza-Closed>
%
pizza:vegetarianToppingsPizza_Closed(I):-rdfs_individual_of(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#VegetarianToppingsPizza-Closed').

%! vegetarianToppingsPizza_Open(I)
%
%  Any instance of <http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#VegetarianToppingsPizza-Open>
%
pizza:vegetarianToppingsPizza_Open(I):-rdfs_individual_of(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#VegetarianToppingsPizza-Open').

%! hasMaterialState(I,J)
%
%  Any relationship of type <http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#hasMaterialState>
%
pizza:hasMaterialState(I,J):-rdf_has(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#hasMaterialState',J).

%! hasTopping(I,J)
%
%  Any relationship of type <http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#hasTopping>
%
pizza:hasTopping(I,J):-rdf_has(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#hasTopping',J).

%! subclass_of_hasMaterialState(I,J)
%
%  As subclass_of_hasMaterialState/2 , TODO
%
pizza:subclass_of_hasMaterialState(I,J):-rdf(I,rdfs:subClassOf,I),rdf(I,owl:onProperty,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#hasMaterialState'),rdf(I,owl:someValuesFrom,J).

%! subclass_of_hasTopping(I,J)
%
%  As subclass_of_hasTopping/2 , TODO
%
pizza:subclass_of_hasTopping(I,J):-rdf(I,rdfs:subClassOf,I),rdf(I,owl:onProperty,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#hasTopping'),rdf(I,owl:someValuesFrom,J).

%! hasMaterialState(I,J,K)
%
%  As hasMaterialState/2  where asserted in graph
%
pizza:hasMaterialState(I,J,K):-rdf(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#hasMaterialState',J,K).

%! hasTopping(I,J,K)
%
%  As hasTopping/2  where asserted in graph
%
pizza:hasTopping(I,J,K):-rdf(I,'http://owl.cs.manchester.ac.uk/2009/07/sssw/pizza#hasTopping',J,K).

